cartlock/urls.py
from django.contrib import admin
from django.urls import path, include
from products import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
]

products/urls.py
from django.urls import path

from . import views

from . views import create_product_view, product_detail_view, cart, checkout

app_name = "products"

urlpatterns = [
	path('', views.products, name="products"),
	path('create-product', create_product_view, name="create_product"),
	path('product/<int:pk>/', product_detail_view.as_view(), name='post_detail'),
	path('cart', cart, name="cart"),
	path('checkout', checkout, name="checkout")
]

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone

from django.urls import reverse

from django.conf import settings

from django.db import models


class Product(models.Model):
    CATEGORY_CHOICES = (
    ('shirts', 'Shirt'),
    ('trousers', 'Trousers & Shorts'),
    ('footwears', 'Footwears'),
    ('others','Others'),
    ('gifts', 'Gifts'),
    )
    user 		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name 		= models.CharField(max_length=150)
    price 		= models.DecimalField(max_digits=9, decimal_places=2)
    description = models.CharField(max_length=500)
    slug    	= models.SlugField(max_length=150, unique_for_date='created')
    image 		= models.ImageField(upload_to='products/%Y/%m/%d')
    seller_info = models.TextField(blank=True, null=True)
    seller_contact = models.IntegerField(blank=True, null=True)
    created		= models.DateTimeField(default=timezone.now)
    updated 	= models.DateTimeField(auto_now=True)
    category    = models.CharField(max_length=25, choices=CATEGORY_CHOICES, default='others')
    is_paid     = models.BooleanField(default=False)


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def price_sign(self):
        strp = str(self.price)
        return strp + " GHS"

    def get_absolute_url(self):
        return reverse('products:post_detail', args = [str(self.pk)] )

products/forms.py
from django import forms

from  . models import Product


class NewProductForm(forms.ModelForm):


	class Meta:
		model = Product
		fields = (
			'name',
			'price',
			'description',
            'category',
			'image',
			'seller_info',
			'seller_contact',
		)

products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django import views

from django.views.generic import DetailView

from . models import Product

from . forms import NewProductForm

from django.contrib.auth.decorators import login_required

# Create your views here.
def products(request):
	products = Product.objects.all()
	return render(request, "products/products.html",  { 'products':products });

#@login_required(login_url='account:login')
def create_product_view(request):
	if request.method == "POST":
		form = NewProductForm(request.POST, request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
		return redirect('products:products')
	else:
		form = NewProductForm()
	return render(request, 'products/new_product.html', { 'form':form })


class product_detail_view(DetailView):
	model = Product
	template_name = 'products/product_detail.html'


def cart(request):
	return render(request, "checkout/cart.html", {});

def checkout(request):
	return render(request, "checkout/checkout.html",  {});

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title> CartLock :: API Testing </title>
</head>
<body>

{% load static %}

<link rel="stylesheet" href="{% static '/css/base.css' %}">

<ul>
	<li><a href="{% url 'products:products' %}"> products </a></li>
	<li><a href="{% url 'products:cart' %}"> cart </a></li>
	<li><a href="{% url 'products:checkout' %}"> checkout </a></li>
</ul>

{% block main %}
{% endblock %}
</body>
</html>

templates/checkout/cart.html
{% extends 'base.html' %}

{% block main %}

<h1> There is no item in this cart because it doesn't work</h1>
{% endblock %}

templates/checkout/checkout.html
{% extends 'base.html' %}

{% block main %}
<h1> Nothing to checkout yet!</h1>
{% endblock %}

templates/products/new_product.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  <div class="product_form">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <p><input type="submit" value="Post"></p>
    </form>
  </div>
</div>
{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
	<div class="product-image" style="float:left">
			<img src="{{ product.image.url }}" />
	</div>
			<div class="product-info">
				<p> This product is being sold by {{ product.user }}</p>
				<p> You can contact the seller on  {{ profile.seller_contact }}</p>
				<p> {{ product.name }} </p>
				<h1> {{ product.price_sign }} </h1>
				<p> {{ product.description }} </p>
				<p> {{ product.seller_info }} </p>
			</div>
</div>
{% endblock %}

templates/products/products.html
{% extends 'base.html' %}

{% block main %}

	<div id="wrapper">
		{% for product in products %}
		<div class="first_grid">
			<div class="product">
				<img src="{{ product.image.url }}">
				<div class="details">
					<p>{{ product.name }}</p>
					<p>Price:  {{ product.price_sign }}</p>
					<li>Free delivery</li>
					<p> <a href="{{ product.get_absolute_url }}"> Details </a></p>
					<a href="{% url 'products:cart' %}">Add to cart</a>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
		
{% endblock %}